"""
app.py — UI only
-----------------
Do not edit this file.
All data comes from data.py
"""

import streamlit as st
import plotly.graph_objects as go
from data import STUDENTS, WEEKS, ACTIONS

st.set_page_config(
    page_title="Taqaddam | Smart Academic Support",
    page_icon="📈",
    layout="wide",
    initial_sidebar_state="collapsed",
)

st.markdown("""
<style>
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
  html, body, [class*="css"] { font-family: 'Inter', sans-serif; }

  .main-header {
    background: #1A5C38;
    color: white;
    padding: 16px 24px;
    border-radius: 14px;
    margin-bottom: 20px;
    display: flex;
    justify-content: space-between;
    align-items: center;
  }
  .logo { font-size: 24px; font-weight: 700; color: #A8D5B5; letter-spacing: 2px; }

  .metric-card {
    background: white;
    border: 1px solid #ebebeb;
    border-radius: 12px;
    padding: 16px 18px;
    text-align: center;
  }
  .metric-val { font-size: 32px; font-weight: 700; line-height: 1; }
  .metric-lbl { font-size: 12px; color: #666; margin-top: 5px; }
  .metric-sub { font-size: 10px; color: #aaa; margin-top: 3px; }

  .student-row {
    background: white;
    border: 1px solid #ebebeb;
    border-radius: 10px;
    padding: 12px 16px;
    margin-bottom: 8px;
    display: flex;
    align-items: center;
    justify-content: space-between;
  }

  .xai-reason {
    background: white;
    border: 1px solid #ebebeb;
    border-left: 3px solid #1A5C38;
    border-radius: 8px;
    padding: 11px 14px;
    margin-bottom: 10px;
  }
  .xai-title { font-size: 13px; font-weight: 600; color: #1a1a1a; margin-bottom: 4px; }
  .xai-desc  { font-size: 12px; color: #555; line-height: 1.7; }

  .action-card {
    background: white;
    border: 1px solid #ebebeb;
    border-radius: 12px;
    padding: 14px 18px;
    margin-bottom: 10px;
  }
  .action-label { font-size: 11px; color: #888; margin-bottom: 5px; }
  .action-value { font-size: 15px; font-weight: 600; color: #1a1a1a; }
  .action-desc  { font-size: 12px; color: #666; margin-top: 4px; line-height: 1.6; }

  /* force white background everywhere */
  .stApp { background-color: white !important; }
  .block-container { padding-top: 1rem; padding-bottom: 2rem; background: white !important; }
  section[data-testid="stSidebar"] { background: white !important; }
  div[data-testid="stToolbar"] { background: white !important; }

  /* fix text colors */
  p, span, div, label { color: #1a1a1a; }
  h1, h2, h3, h4 { color: #1a1a1a !important; }

  #MainMenu, footer, header { visibility: hidden; }
</style>
""", unsafe_allow_html=True)

# ── Session state ──────────────────────────────────────────────────────────────
if "screen" not in st.session_state:
    st.session_state.screen = "dashboard"
if "selected_student" not in st.session_state:
    st.session_state.selected_student = None

# ── Header ─────────────────────────────────────────────────────────────────────
st.markdown("""
<div class="main-header">
  <div>
    <div style="font-size:13px;opacity:.85">AI-Powered Academic Support System</div>
    <div style="font-size:11px;opacity:.65;margin-top:2px">
      Academic Advisor | Prince Sattam bin Abdulaziz University
    </div>
  </div>
  <div class="logo">TAQADDAM</div>
</div>
""", unsafe_allow_html=True)

# ── Navigation tabs ────────────────────────────────────────────────────────────
SCREENS = ["dashboard", "profile", "why", "action"]
LABELS  = ["📊  Dashboard", "👤  Student Profile", "🔍  Why This Student?", "✅  Suggested Action"]
cur_idx = SCREENS.index(st.session_state.screen)

for i, (label, screen) in enumerate(zip(LABELS, SCREENS)):
    with st.columns(4)[i]:
        if st.button(label, use_container_width=True,
                     type="primary" if i == cur_idx else "secondary",
                     disabled=(i > cur_idx and not st.session_state.selected_student)):
            st.session_state.screen = screen
            st.rerun()

st.divider()

# ══════════════════════════════════════════════════════════════════
# SCREEN 1 — Dashboard
# ══════════════════════════════════════════════════════════════════
if st.session_state.screen == "dashboard":

    if not STUDENTS:
        st.info("Waiting for model data...")
        st.stop()

    high  = sum(1 for s in STUDENTS if s["risk"] == "high")
    med   = sum(1 for s in STUDENTS if s["risk"] == "medium")
    total = len(STUDENTS)
    pct   = round((high + med) / total * 100)

    # KPI cards
    cols = st.columns(5)
    kpis = [
        (total,    "#1a1a1a", "Total Students",    "Current semester"),
        (high,     "#A32D2D", "High Risk 🔴",       "Immediate action"),
        (med,      "#BA7517", "Medium Risk 🟡",     "Periodic follow-up"),
        ("—",      "#185FA5", "Avg Engagement",    ""),
        (f"{pct}%","#1A5C38", "Need Support",      "of total students"),
    ]
    for col, (val, color, lbl, sub) in zip(cols, kpis):
        with col:
            st.markdown(f"""
            <div class="metric-card">
              <div class="metric-val" style="color:{color}">{val}</div>
              <div class="metric-lbl">{lbl}</div>
              <div class="metric-sub">{sub}</div>
            </div>""", unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)
    st.markdown(f"**Students needing support — {pct}%**")

    fig_bar = go.Figure(go.Bar(
        x=[pct, 100 - pct], y=[""], orientation="h",
        marker_color=["#1A5C38", "#e8f5ee"], hoverinfo="skip", width=0.4,
    ))
    fig_bar.update_layout(
        height=55, margin=dict(l=0, r=0, t=0, b=0),
        showlegend=False, barmode="stack",
        plot_bgcolor="rgba(0,0,0,0)", paper_bgcolor="rgba(0,0,0,0)",
        xaxis=dict(visible=False), yaxis=dict(visible=False),
    )
    st.plotly_chart(fig_bar, use_container_width=True, config={"displayModeBar": False})

    st.markdown("### Students Ranked by Priority")

    RISK_STYLE = {
        "high":   ("#FCEBEB", "#A32D2D", "High Risk"),
        "medium": ("#FFF3CD", "#854F0B", "Medium Risk"),
        "low":    ("#E8F5EE", "#1A5C38", "Low Risk"),
    }

    for s in STUDENTS:
        bg, fg, badge_txt = RISK_STYLE[s["risk"]]
        c1, c2, c3 = st.columns([4, 2, 1])
        with c1:
            st.markdown(f"""
            <div style="padding:8px 0">
              <div style="font-size:15px;font-weight:600;color:#1a1a1a">{s['name']}</div>
              <div style="font-size:12px;color:#777;margin-top:2px">
                {s['major']} · {s['level']} · Support Index: {s['support_index']}%
              </div>
            </div>""", unsafe_allow_html=True)
        with c2:
            st.markdown(
                f"<br><span style='background:{bg};color:{fg};"
                f"padding:4px 12px;border-radius:20px;font-size:12px;font-weight:600'>"
                f"{badge_txt}</span>",
                unsafe_allow_html=True,
            )
        with c3:
            st.markdown("<br>", unsafe_allow_html=True)
            if st.button("View →", key=f"v{s['id']}"):
                st.session_state.selected_student = s
                st.session_state.screen = "profile"
                st.rerun()
        st.divider()

# ══════════════════════════════════════════════════════════════════
# SCREEN 2 — Student Profile
# ══════════════════════════════════════════════════════════════════
elif st.session_state.screen == "profile":
    s = st.session_state.selected_student

    st.markdown(f"""
    <div style="background:#1A5C38;color:white;border-radius:12px;
                padding:20px 24px;margin-bottom:18px">
      <div style="display:flex;justify-content:space-between;align-items:flex-start">
        <div>
          <div style="font-size:20px;font-weight:700">{s['name']}</div>
          <div style="font-size:12px;opacity:.85;margin-top:3px">
            {s['major']} · {s['level']}
          </div>
        </div>
        <span style="background:rgba(255,255,255,.2);color:white;border-radius:20px;
                     padding:5px 14px;font-size:13px;font-weight:600">
          {s['risk_label']}
        </span>
      </div>
      <div style="display:grid;grid-template-columns:1fr 1fr 1fr;gap:10px;margin-top:16px">
        <div style="background:rgba(255,255,255,.18);border-radius:8px;
                    padding:10px;text-align:center">
          <div style="font-size:24px;font-weight:700">{s['support_index']}%</div>
          <div style="font-size:10px;opacity:.8;margin-top:2px">Support Index</div>
        </div>
        <div style="background:rgba(255,255,255,.18);border-radius:8px;
                    padding:10px;text-align:center">
          <div style="font-size:24px;font-weight:700">{s['avg_grade']}%</div>
          <div style="font-size:10px;opacity:.8;margin-top:2px">Avg Grade</div>
        </div>
        <div style="background:rgba(255,255,255,.18);border-radius:8px;
                    padding:10px;text-align:center">
          <div style="font-size:24px;font-weight:700">{s['avg_delay']}</div>
          <div style="font-size:10px;opacity:.8;margin-top:2px">Avg Delay (days)</div>
        </div>
      </div>
    </div>""", unsafe_allow_html=True)

    cl, cr = st.columns(2)

    with cl:
        fig_g = go.Figure(go.Scatter(
            x=WEEKS, y=s["grades"], mode="lines+markers",
            line=dict(color="#1A5C38", width=2.5),
            marker=dict(size=7, color="#1A5C38"),
            fill="tozeroy", fillcolor="rgba(26,92,56,0.08)",
        ))
        fig_g.update_layout(
            title="Grade Trend", height=220,
            margin=dict(l=10, r=10, t=36, b=10),
            yaxis=dict(range=[40, 100]),
            plot_bgcolor="white", paper_bgcolor="white",
            showlegend=False, font=dict(family="Inter"),
        )
        st.plotly_chart(fig_g, use_container_width=True, config={"displayModeBar": False})

    with cr:
        ec = ["#2D8B4E" if v >= 15 else "#BA7517" if v >= 8 else "#A32D2D"
              for v in s["engagement"]]
        fig_e = go.Figure(go.Bar(
            x=WEEKS, y=s["engagement"],
            marker_color=ec, text=s["engagement"],
            textposition="outside", width=0.5,
        ))
        fig_e.update_layout(
            title="Weekly Engagement (login sessions)", height=220,
            margin=dict(l=10, r=10, t=36, b=10),
            yaxis=dict(range=[0, max(s["engagement"]) + 5]),
            plot_bgcolor="white", paper_bgcolor="white",
            showlegend=False, font=dict(family="Inter"),
        )
        st.plotly_chart(fig_e, use_container_width=True, config={"displayModeBar": False})

    st.markdown("#### Submission Delays")
    d_v = [5 if d is None else d for d in s["delays"]]
    d_l = [
        "Not submitted" if d is None
        else ("On time" if d == 0 else f"{d} {'day' if d == 1 else 'days'}")
        for d in s["delays"]
    ]
    d_c = [
        "#791F1F" if d is None
        else "#A32D2D" if d >= 4
        else "#BA7517" if d >= 2
        else "#2D8B4E"
        for d in s["delays"]
    ]
    fig_d = go.Figure(go.Bar(
        x=WEEKS, y=d_v, marker_color=d_c,
        text=d_l, textposition="outside", width=0.5,
    ))
    fig_d.update_layout(
        height=190, margin=dict(l=10, r=10, t=10, b=10),
        yaxis=dict(range=[0, 8], visible=False),
        plot_bgcolor="white", paper_bgcolor="white",
        showlegend=False, font=dict(family="Inter"),
    )
    st.plotly_chart(fig_d, use_container_width=True, config={"displayModeBar": False})

    if st.button("Why This Student? →", type="primary", use_container_width=True):
        st.session_state.screen = "why"
        st.rerun()

# ══════════════════════════════════════════════════════════════════
# SCREEN 3 — XAI
# ══════════════════════════════════════════════════════════════════
elif st.session_state.screen == "why":
    s = st.session_state.selected_student

    st.markdown(f"### Explanation for **{s['name']}** — {s['risk_label']}")

    names  = [f["name"] for f in s["xai_factors"]]
    vals   = [f["importance"] for f in s["xai_factors"]]
    colors = ["#A32D2D" if v >= 70 else "#BA7517" if v >= 45 else "#888" for v in vals]

    fig_x = go.Figure(go.Bar(
        x=vals, y=names, orientation="h",
        marker_color=colors,
        text=[f"{v}%" for v in vals], textposition="outside",
    ))
    fig_x.update_layout(
        title="Feature Importance (XAI)", height=230,
        margin=dict(l=10, r=60, t=40, b=10),
        xaxis=dict(range=[0, 115], ticksuffix="%"),
        plot_bgcolor="white", paper_bgcolor="white",
        showlegend=False, font=dict(family="Inter"),
    )
    st.plotly_chart(fig_x, use_container_width=True, config={"displayModeBar": False})

    st.markdown("#### Top Reasons")
    for r in s["xai_reasons"]:
        st.markdown(f"""
        <div class="xai-reason">
          <div class="xai-title">{r['title']}</div>
          <div class="xai-desc">{r['desc']}</div>
        </div>""", unsafe_allow_html=True)

    if st.button("Suggested Action →", type="primary", use_container_width=True):
        st.session_state.screen = "action"
        st.rerun()

# ══════════════════════════════════════════════════════════════════
# SCREEN 4 — Action
# ══════════════════════════════════════════════════════════════════
elif st.session_state.screen == "action":
    s = st.session_state.selected_student
    a = ACTIONS.get(s["risk"], ACTIONS["low"])

    priority_label, priority_color = a["priority"]
    followup_label, followup_color = a["followup"]

    st.markdown(f"""
    <div class="action-card" style="border-left:4px solid {priority_color}">
      <div style="font-size:12px;color:#888;margin-bottom:5px">Intervention Priority</div>
      <div style="font-size:22px;font-weight:700;color:{priority_color}">{priority_label}</div>
      <div style="font-size:12px;color:#666;margin-top:5px">
        Recommended contact within {a['hours']} hours
      </div>
    </div>""", unsafe_allow_html=True)

    c1, c2 = st.columns(2)
    with c1:
        st.markdown(f"""
        <div class="action-card">
          <div class="action-label">📋 Recommended Action</div>
          <div class="action-value">{a['recommendation']}</div>
          <div class="action-desc">{a['rec_desc']}</div>
        </div>
        <div class="action-card">
          <div class="action-label">👤 Human Follow-up Needed?</div>
          <div class="action-value" style="color:{followup_color}">{followup_label}</div>
          <div class="action-desc">{a['followup_desc']}</div>
        </div>""", unsafe_allow_html=True)
    with c2:
        st.markdown(f"""
        <div class="action-card">
          <div class="action-label">🎯 Support Type</div>
          <div class="action-value">{a['support_type']}</div>
          <div class="action-desc">{a['support_desc']}</div>
        </div>
        <div class="action-card">
          <div class="action-label">⚡ Priority within Semester</div>
          <div class="action-value" style="color:#1A5C38">Top 15%</div>
          <div class="action-desc">
            Support index {s['support_index']}% compared to other students
          </div>
        </div>""", unsafe_allow_html=True)

    st.markdown("#### Suggested Message")
    st.text_area(
        "Edit before sending",
        value=(f"Hello {s['name']}, I hope you're doing well. "
               f"I'd like to schedule a brief meeting this week to discuss "
               f"your study plan and progress. Would Wednesday or Thursday work for you?"),
        height=100,
    )

    ca, cb = st.columns(2)
    with ca:
        if st.button("✓ Student Contacted", type="primary", use_container_width=True):
            st.success(f"Contact with {s['name']} has been logged ✓")
    with cb:
        if st.button("↩ Back to Dashboard", use_container_width=True):
            st.session_state.screen = "dashboard"
            st.session_state.selected_student = None
            st.rerun()
